apiVersion: v1
kind: Service
metadata:
  name: {{ include "bloom.fullname" . }}
  labels:
    {{- include "bloom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.control.port }}
      targetPort: control
      protocol: TCP
      name: control
  selector:
    {{- include "bloom.selectorLabels" . | nindent 4 }}
